from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('Chinese_font_library', src, depend = ['PKG_USING_Chinese_font_library'], CPPPATH = CPPPATH)

Return('group')